name: Publish package
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: "publish"
        env:
          MAVEN_DEPLOY_USERNAME: ${{ secrets.OPENCOLLAB_USERNAME }}
          MAVEN_DEPLOY_PASSWORD: ${{ secrets.OPENCOLLAB_PASSWORD }}
          PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_PASSPHRASE }}
          MAVEN_DEPLOY_URL: "https://repo.opencollab.dev/maven-snapshots/"